### ISSUE TITLE
/mermaid/svg cuts off text regardless of style width

### ISSUE THREAD

**Issue by working-name** [yuzutech/kroki#1317] opened 2022-08-24 16:43 UTC
Hello there,

Any way to make this look decent?
https://kroki.io/mermaid/svg/eNpLy8kvT85ILCpRCHHi4kzR8PD11VTQ1bWrcS4tKcnMS1fIrVQoLilNS6tRCPeI5FIAguKSypxUhRSFtMycHCvlNGMQ1CnPTCnJsLIwLagAADxOGig=

```js
flowchart TB
    d(HMM) -->|Cutting my stuff| WHY
    style d fill:#f3f3f3,width:85px
```

```mermaid
flowchart TB
    d(HMM) -->|Cutting my stuff| WHY
    style d fill:#f3f3f3,width:85px
```
^ this is rendered by github I'm assuming, which is why it's not clipping the last letter of each word.

Thank you!

**Comment by Mogztter** [comment] 2022-08-24 21:03
I believe it's a duplicate of https://github.com/yuzutech/kroki/issues/1298
This issue was fixed in https://github.com/yuzutech/kroki/commit/97cfa25c4811cfb49ac2cf1e8186b047390d8c49 and will be available in the next release.

**Closed** 2022-08-24 21:03 UTC
Labels: duplicate

**Comment by working-name** [comment] 2022-08-25 10:56
My mistake, I searched for the wrong keywords I suppose. Thank you!

**Comment by Mogztter** [comment] 2022-08-26 07:25
No worries 😉 
I will take your example to make sure that everything is working as expected before releasing.
