### ISSUE TITLE
for mermaid， sometimes the right margin is too small

### ISSUE THREAD

**Issue by imysl0** [yuzutech/kroki#1736] opened 2024-04-09 15:25 UTC
Using Kroki, there is a blur at the arrow, indicating that the right margin is too small
![image](https://github.com/yuzutech/kroki/assets/17337930/36f5df27-9f04-4974-86fb-5a48b839a424)
Using mermaid, no blur
![image](https://github.com/yuzutech/kroki/assets/17337930/f36741a8-8662-4b41-b263-9eb60ab206e3)

this is code：
```mermaid
---
title: ABCD_TOPL_ID mermaid
---
stateDiagram-v2
[*] --> ABCD_L_L0
ABCD_L_L0 --> ABCD_L_L1
ABCD_L_L0 --> ABCD_L_LT
ABCD_L_L1 --> ABCD_L_L2
ABCD_L_L1 --> ABCD_L_LT
ABCD_L_L2 --> ABCD_L_L3
ABCD_L_L2 --> ABCD_L_LT
ABCD_L_L3 --> ABCD_L_LT
ABCD_L_LT --> [*] 
```

**Comment by imysl0** [comment] 2024-04-09 15:26
```txt
---
title: ABCD_TOPL_ID mermaid
---
stateDiagram-v2
[*] --> ABCD_L_L0
ABCD_L_L0 --> ABCD_L_L1
ABCD_L_L0 --> ABCD_L_LT
ABCD_L_L1 --> ABCD_L_L2
ABCD_L_L1 --> ABCD_L_LT
ABCD_L_L2 --> ABCD_L_L3
ABCD_L_L2 --> ABCD_L_LT
ABCD_L_L3 --> ABCD_L_LT
ABCD_L_LT --> [*] 
```

**Comment by gladykov** [comment] 2024-07-04 13:54
Another example:

```
classDiagram

class MQTTDevice {
	-deviceCount: int
	-idiotDevices: mqttDevice_t[]
	
	+mqtt_handleApplianceMessage(string, string, mqttDevice_t) void 
	+mqtt_deviceGetVersionJson(string, size_t, mqttDevice_t) bool 
	+mqtt_getDeviceCount() int 
	+mqtt_getDeviceBySerial(string) mqttDevice_t
	+mqtt_getDeviceByIndex(int) mqttDevice_t
	+mqtt_registerIdiotDevice(idiot_device_t) void 
	-_getTopicHandler(string, mqttDevice_t) msgHandler_t
	-_controlMsgHandler(json_t, mqttDevice_t) void
}
```

results in:

![image](https://github.com/yuzutech/kroki/assets/24669884/29935b2c-f243-48d6-8daa-3d0b0013a889)

**Comment by ggrossetie** [comment] 2024-07-11 07:06
This is a duplicate of https://github.com/yuzutech/kroki/issues/1345

**Closed by ggrossetie** 2024-07-11 07:06 UTC
