### ISSUE TITLE
actdiag: delivered pdf has no content

### ISSUE THREAD

**Issue by deining** [yuzutech/kroki#1471] opened 2023-03-15 13:22 UTC
According to the [docs](https://kroki.io/#support), `pdf` is supported as output format for `actdiag` diagrams.

I can succesfully retrieve a pdf:

```
$ http https://kroki.io/ diagram_type='actdiag' output_format='pdf' diagram_source="{ lane MyLane { write [label = 'My label']; } }" 
```

Regardless of the diagram source text, the delivered pdf is always empty. The only thing that changes inside the pdf file is the creation and the modification date.

**Comment by ggrossetie** [comment] 2023-03-18 17:13
I can confirm this issue.
Something is wrong with reportlab. It might be broken since we've upgraded from ReportLab 3.5 to 3.6.

**Comment by ggrossetie** [comment] 2023-08-14 14:53
This is fixed in https://github.com/yuzutech/kroki/pull/1613

**Closed by ggrossetie** 2023-08-14 14:53 UTC
Labels: 🐞 bug, :wave: help wanted, 👀 investigating
