### ISSUE TITLE
[BUG]excalidraw occupies CPU very highly

### ISSUE THREAD

**Issue by mrmign** [yuzutech/kroki#1177] opened 2022-03-05 13:37 UTC
![image](https://user-images.githubusercontent.com/1880532/156885476-2d19867c-ffba-4f5f-9ce1-2d337764945f.png)

as the screenshot showed, the excalidraw container occupies CPU over 100%, the fan is running crazily.

**Comment by Mogztter** [comment] 2022-03-05 14:06
Probably related to https://github.com/yuzutech/kroki/issues/1037 if you are running Kroki 0.16.0.

**Comment by Mogztter** [comment] 2022-03-07 11:15
I will assume that this is a duplicate of #1037, feel free to reopen if that's not the case.

**Closed by Mogztter** 2022-03-07 11:15 UTC
