### ISSUE TITLE
KROKI_SAFE_MODE doesn't work with Docker image

### ISSUE THREAD

**Issue by vincent-smit** [yuzutech/kroki#369] opened 2020-09-07 08:41 UTC
I am trying to use an external include server but it seems Kroki doesn't work with passing the DKROKI_SAFE_MODE environment variable to the Docker image. When I run the stand-alone JAR file it works without any problems.

`docker run -p8080:8000 -d yuzutech/kroki --env KROKI_SAFE_MODE=unsafe
`

Any idea how to make this work?

**Comment by Mogztter** [comment] 2020-09-07 09:12
Hello @vincent-smit 

The environment variable should be declared before the image name in your command.
The following should work:

```
docker run -p8080:8000 --env KROKI_SAFE_MODE=unsafe -d yuzutech/kroki
```

**Comment by vincent-smit** [comment] 2020-09-07 15:50
@Mogztter  Thanks for the quick reply, it seems to almost work.. I when I preview my diagram with the VSCode PlantUML plugin the diagram is shown briefly (a few miliseconds) before it disappears. I extracted the following logging from the container, any ideas? (I removed some part of url..)

`{
  "timestamp": "1599493539439",
  "level": "ERROR",
  "thread": "vert.x-eventloop-thread-0",
  "mdc": {
    "error_message": "Syntax Error? (line: 10)",
    "path": "/c4plantuml/svg/bLB1Rjim3BtxArZlagABZQsNROUXMLEq1PeYQ9RsB4jqB4oMF8bAsdtzABjk0gmhq8iWKU_nyP4y2oGynTO0NA4n3XwSDohBZXJMsYBC_aIFo_JV47NXMrbwiIiscffOnO1UEajegP2kBU-q55wvMuqTch9dJfT6M5elRagF1aN0ylFqKwbqeEn8MscYmkZDNcLWdRksTRReEF0V62EwI3Z0xpKx46OXPCCblqMxHTev_qlRpS2STPtXeaaxUoa8T-BfBVPSaAZOGnZ8gzzcZBnBCntpkLijlIEKIVizz1idr0_1NPNe1rwM6Qm9o87NcuP0QJ-avH-nuU50_g0jf6db80Bij4rt-53NDKDUQU6ay-xnwIFawo",
    "method": "GET",
    "action": "error",
    "error_code": "400",
    "failure_class_name": "io.kroki.server.error.BadRequestException"
  },
  "logger": "io.kroki.server.error.ErrorHandler",
  "message": "An error occurred",
  "context": "default",
  "exception": "io.kroki.server.error.BadRequestException: Syntax Error? (line: 10)\n\tat io.kroki.server.service.Plantuml.convert(Plantuml.java: 205)\n\tat io.kroki.server.service.C4Plantuml.convert(C4Plantuml.java: 73)\n\tat io.kroki.server.service.DiagramHandler.convert(DiagramHandler.java: 152)\n\tat io.kroki.server.service.DiagramHandler.lambda$createGet$1(DiagramHandler.java: 56)\n\tat io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java: 1034)\n\tat io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java: 95)\n\tat io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java: 133)\n\tat io.kroki.server.service.DiagramHandler.lambda$createRequestReceived$0(DiagramHandler.java: 38)\n\tat io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java: 1034)\n\tat io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java: 131)\n\tat io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java: 133)\n\tat io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java: 125)\n\tat io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java: 38)\n\tat io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java: 1034)\n\tat io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java: 131)\n\tat io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java: 133)\n\tat io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java: 54)\n\tat io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java: 36)\n\tat io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java: 50)\n\tat io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java: 32)\n\tat io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java: 136)\n\tat io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java: 366)\n\tat io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java: 43)\n\tat io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java: 229)\n\tat io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java: 173)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java: 357)\n\tat io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java: 93)\n\tat io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java: 101)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java: 357)\n\tat io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java: 109)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java: 357)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java: 324)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java: 296)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java: 357)\n\tat io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java: 61)\n\tat io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java: 38)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java: 357)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java: 1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java: 365)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java: 919)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java: 163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java: 714)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java: 650)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java: 576)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java: 493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java: 989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java: 74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java: 30)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"
}`

**Comment by Mogztter** [comment] 2020-09-07 16:03
Not sure, you should check your syntax, the server returns:

```
Syntax Error? (line: 10)
```

But the following URL does not work because the content is not correctly encoded:

https://kroki.io/c4plantuml/svg/bLB1Rjim3BtxArZlagABZQsNROUXMLEq1PeYQ9RsB4jqB4oMF8bAsdtzABjk0gmhq8iWKU_nyP4y2oGynTO0NA4n3XwSDohBZXJMsYBC_aIFo_JV47NXMrbwiIiscffOnO1UEajegP2kBU-q55wvMuqTch9dJfT6M5elRagF1aN0ylFqKwbqeEn8MscYmkZDNcLWdRksTRReEF0V62EwI3Z0xpKx46OXPCCblqMxHTev_qlRpS2STPtXeaaxUoa8T-BfBVPSaAZOGnZ8gzzcZBnBCntpkLijlIEKIVizz1idr0_1NPNe1rwM6Qm9o87NcuP0QJ-avH-nuU50_g0jf6db80Bij4rt-53NDKDUQU6ay-xnwIFawo

So it might be a bug in the plugin (i.e. the content is not correctly encoded by the plugin).

>  I when I preview my diagram with the VSCode PlantUML plugin the diagram is shown briefly (a few miliseconds) before it disappears.

Did you mean the VSCode Asciidoctor plugin? I'm not sure how the VSCode PlantUML plugin will work with Kroki... :thinking:

**Comment by Mogztter** [comment] 2020-09-09 17:56
@vincent-smit did you find the root cause? if you can share a simple reproduction case, I can give it a try on my machine.

**Comment by Mogztter** [comment] 2020-09-15 19:49
This is excellent news, thanks for letting me know 👍 
Closing 🚪 😉

**Closed by Mogztter** 2020-09-15 19:49 UTC
Labels: :grey_question: question
