### ISSUE TITLE
Feature Request: Support for Wardley Maps

### ISSUE THREAD

**Issue by emerzon** [yuzutech/kroki#1707] opened 2024-02-09 19:38 UTC
Sample UI: https://www.onlinewardleymaps.com/

Rendering engine exists at: https://github.com/damonsk/onlinewardleymaps

Some examples: https://github.com/damonsk/wardley-maps-examples

Would it possible to integrate this functionality?

**Comment by ggrossetie** [comment] 2024-02-10 12:13
This is a duplicate of https://github.com/yuzutech/kroki/issues/179

**Closed by ggrossetie** 2024-02-10 12:13 UTC
