### ISSUE TITLE
UMlet: Renders with errors (regression in 0.21.0)

### ISSUE THREAD

**Issue by gladykov** [yuzutech/kroki#1618] opened 2023-08-18 15:01 UTC
Steps to reproduce:

1. Check UMlet [example](https://kroki.io/umlet/svg/eNrdWUFv2jAYvedXRBym7lBiJ05ChEkvU7Ve1047VFNlEgNZQ4IcU8q_n51ip5SujRHNoAcwmCTye9_3vvfZWPjicZ7bD5RVWVmMerAPejYtkjLNiumo9_Pm8nzQu4jxcp5TfpdmZMrIPMY0p3Na8Bjz9YLGSTnv1xf0N_P9Malo_wfNCRdPxU59FU7KkonHEk6rGD_GoRdh5zHG6xgG2FnHeBW7noudVYxnsRsg7Mxi7GzdtCAFze8I5ywbL-VMzkdfcj48t1YzWpxViywVQGhRlWzUYyUXd_W-Ws44L5N7--lX7Ow8BJM0zeRCydY0DODQRWgoRw8NQ_UeipW9fgd2NC_vEZQsKy4mLwWy_Fqu8x8kDSKwIckNgGIJKJJAG47aI-aMFNWCMLHAa7HQRF4xmpC8ogdA3ColfIUWhgotDBRc6IVGOUEmnDL7DIJK5IC9ZxIgMIQADINADZL0Q4X_rch7SHGBXM0FUFygVqFfkYwfSfg3iL9nYmDrt4C7ngaOPn_KP0OryyD0FFzfrAoyWnHCDELuAlnUIJRDV4BDBdiLFOBoT7wLspSBaos2rNG6BwLbtoTrCo7A509nFCi78nU2Q6QKuKGpbxVwns1puTTIbV8ktrBvMYigR6jDDNeSFsJSJOgUr53NgARj3CK_oQ9qUatRToWgM-sKgSIg0vgHGj9ohZ8kCV1wa1wSedHUXpCqss7PLbEEtnZsJpYjQmEn4mcrLR313dTfXxUMZ8uu9OJrl4fPzM4340rnyq1kiRZToZpxWd7T9LdJu_uUJ-I1qD8NQFc1Q3d9rtaLKzcHTxxEe3NQlNycBxdGtVgiPXQlm6BxRl_rRluF34oGRv-IJN6WzSnZx0DLwdMUIHdPOYh2aJlzu5zYFSUsmRl0ClCKQLy7oPO2qNn5-GbdvsJtoHmvVrp7WGu4mTFKf5F169L3TPYn2Ri10DbUYINXwuu21DZJ7ZeGeBxW14IBBHYZ0E1BuxqfzKjYwuv63rQD9a5nI3LZDYzzrLi3czJfHBU9724VYNhsBj-_JBrbR_secEhJWI3hX307Rfiety980esWPJusGwpOyOvrg70XR5vIrCCYO56wuvBwhmcGE4IdmOHHwfT_F8ymedUwBx8HM-gYJto9oQ4HeyWtdftA8sxka-JFMnm97nYkTY2C_r41qjZtq4aa8fVx1eerQjymrSXDIz--c7b_o7P-At8zCQE=) from https://kroki.io/examples.html#state-machine

Result:
Errors

![image](https://github.com/yuzutech/kroki/assets/24669884/202ed53d-b371-4815-9060-acd8eca53217)

It didn't occur in 0.20.0
In [0.21.0](https://github.com/yuzutech/kroki/compare/v0.20.0...v0.21.0) 
- UMlet was bumped to 15.1
- native library started to be used https://github.com/yuzutech/kroki/commit/a08cdfc03b66fa2a4dfd547edac93e5b6961cb1b

Using same input file I checked UMlet standalone 15.1 from https://github.com/umlet/umlet and it renders properly to SVG:
`java -jar umlet.jar -action=convert -format=svg -filename=diagram_umlet_in.uxf -output=.`

Note:
Exissts also in 0.22

**Comment by ggrossetie** [comment] 2023-08-19 13:06
I cannot transfer this issue to https://github.com/yuzutech/umlet but it will be fixed over there

**Comment by ggrossetie** [comment] 2023-08-20 09:32
I can reproduce this issue 👍🏻

**Comment by ggrossetie** [comment] 2023-08-20 13:56
Fixed on the latest release: https://github.com/yuzutech/umlet/releases/tag/2023-03-20_UMLet_v15.1
We need to rebuild the Docker image to fetch the latest version.

**Comment by ggrossetie** [comment] 2023-08-20 13:56
In other words, it will be fixed on the next release.

**Closed by ggrossetie** 2023-08-20 13:56 UTC
Labels: 🐞 bug

**Comment by gladykov** [comment] 2023-08-21 02:01
Thank you sir :smiley:

**Comment by iriswang233** [comment] 2024-01-04 07:59
hi is the fix released?

**Comment by ggrossetie** [comment] 2024-01-04 22:58
If you cannot reproduce this issue on the latest version (or on https://kroki.io/) then it's released.
