### ISSUE TITLE
The mermaid companion container errors on startup

### ISSUE THREAD

**Issue by groovytron** [yuzutech/kroki#8] opened 2019-04-24 06:15 UTC
# The current behaviour

The mermaid companion seems to be broken and shows this error:

```log
Unable to start the service Error: Failed to launch chrome
```

Output of `docker-compose up`:

```log
blockdiag_1  | [2019-04-24 06:09:02 +0000] [1] [INFO] Starting gunicorn 19.9.0
blockdiag_1  | [2019-04-24 06:09:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:8001 (1)
blockdiag_1  | [2019-04-24 06:09:02 +0000] [1] [INFO] Using worker: sync
blockdiag_1  | [2019-04-24 06:09:02 +0000] [7] [INFO] Booting worker with pid: 7
mermaid_1    | Unable to start the service Error: Failed to launch chrome!
mermaid_1    | 
mermaid_1    | 
mermaid_1    | TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
mermaid_1    | 
mermaid_1    |     at onClose (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:342:14)
mermaid_1    |     at Interface.helper.addEventListener (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:331:50)
mermaid_1    |     at Interface.emit (events.js:187:15)
mermaid_1    |     at Interface.close (readline.js:379:8)
mermaid_1    |     at Socket.onend (readline.js:157:10)
mermaid_1    |     at Socket.emit (events.js:187:15)
mermaid_1    |     at endReadableNT (_stream_readable.js:1081:12)
mermaid_1    |     at process._tickCallback (internal/process/next_tick.js:63:19)
kroki-stack_mermaid_1 exited with code 1
kroki_1      | Apr 24, 2019 6:09:03 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
kroki_1      | INFO: Succeeded in deploying verticle
```
docker-compose.yaml:

```yaml
version: "3"
services:
  kroki:
    image: yuzutech/kroki:0.0.4
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
    ports:
      - "8000:8000"
  blockdiag:
    image: yuzutech/kroki-blockdiag:0.0.4
    ports:
      - "8001:8001"
  mermaid:
    image: yuzutech/kroki-mermaid:0.0.4
    ports:
      - "8002:8002"
```

# Expected behaviour

The container should start and wait for HTTP requests.

# Way to reproduce the error

1. Put the `docker-compose.yml` in a directory
2. Run `docker-compose up` in this directory

Thanks in advance for your help.

**Comment by Mogztter** [comment] 2019-04-24 08:10
Hello @groovytron and thanks for the detailed report! 

It's working fine on my machine but I've experienced a few issues with Puppeteer outside Docker: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

Could you try to run the following command to make sure that this issue is not related to `docker-compose` ?

```
$ docker run yuzutech/kroki-mermaid:0.0.4
```

Also can I ask what is the Linux distribution on your host machine ? Are you running `docker` as `root` ? What version of `docker` are your using ?

For reference here's what I get on my machine:

```
$ docker -v
Docker version 18.09.5, build e8ff056
```
```
$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

```
$ docker run yuzutech/kroki-mermaid:0.0.4
Chrome accepting connections on endpoint ws://127.0.0.1:33217/devtools/browser/586b0be5-6f0c-4c2b-895f-227bee17cf6c
```

**Comment by groovytron** [comment] 2019-04-24 09:55
Thank you for this fast reply. Here are the information you asked.

> Could you try to run the following command to make sure that this issue is not related to docker-compose ?

```console
$ docker run yuzutech/kroki-mermaid:0.0.4
Unable to start the service Error: Failed to launch chrome!


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

> Also can I ask what is the Linux distribution on your host machine ? Are you running docker as root ? What version of docker are your using ?

```console
$ cat /etc/*-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

```console
$ docker -v
Docker version 18.09.5-ce, build e8ff056dbc
```

I don't run `docker` as `root` but I'm in the `docker` group in my machine (configured following t[he Arch Linux wiki recommendations](https://wiki.archlinux.org/index.php/Docker)).

**Comment by Mogztter** [comment] 2019-04-24 10:59
Thanks!
So we are using the same image with the same version of Docker but on a different host.

I will upgrade to the latest version of Puppeteer and publish a new version. Hopefully it will fix this issue.
If not, I will publish an image with only Puppeteer as described in: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-on-alpine (to make it easier to find the root cause).

**Comment by Mogztter** [comment] 2019-04-24 14:26
@groovytron I've just published `yuzutech/kroki-mermaid:0.0.5` on Docker hub, could you please give it a try ?

I'm not really convinced but who knows :wink: 

> I don't run docker as root but I'm in the docker group in my machine (configured following the Arch Linux wiki recommendations).

This is definitely the right approach but for testing purpose could you try to run as `root` to see if there are any changes ?

**Comment by groovytron** [comment] 2019-04-24 15:25
Thanks for this new image.

Here is the result when I run `docker run yuzutech/kroki-mermaid:0.0.5` as my standard user:

```console
$ docker run yuzutech/kroki-mermaid:0.0.5
Unable to find image 'yuzutech/kroki-mermaid:0.0.5' locally
0.0.5: Pulling from yuzutech/kroki-mermaid
169185f82c45: Already exists 
90b406d1be33: Pull complete 
4ba560d92217: Pull complete 
231374e8951d: Pull complete 
Digest: sha256:d77b2a2ddf6b409cd00720238eb92af1b756400ced94ba3890fd3b83746b850f
Status: Downloaded newer image for yuzutech/kroki-mermaid:0.0.5
Unable to start the service Error: Failed to launch chrome!


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

And here is the result when I run `docker run yuzutech/kroki-mermaid:0.0.5` as `root` (`su root` before running docker):

```console
# docker run yuzutech/kroki-mermaid:0.0.5
Unable to start the service Error: Failed to launch chrome!


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Mogztter** [comment] 2019-04-25 05:57
Ok, so the good news is that we get the same error when running as root or not.

The error message is really not explicit at all, I will try to make it more verbose.

**Comment by Mogztter** [comment] 2019-04-25 07:37
I don't understand why we do not have the root cause.
When I remove the `--no-sandox`, I get the following error:

```console
$ docker run yuzutech/kroki-mermaid:latest
Unable to start the service Error: Failed to launch chrome!
[0425/071752.910109:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

As you can see, I have an explicit error message:

```
[0425/071752.910109:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

Puppeteer is using the following code to output the error message:

```js
    function onClose(error) {
      cleanup();
      reject(new Error([
        'Failed to launch chrome!' + (error ? ' ' + error.message : ''),
        stderr,
        '',
        'TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md',
        '',
      ].join('\n')));
    }
```

So in that case, the error is `undefined` or the message is empty :disappointed: 

@groovytron I've updated the Docker image to use the latest version of Alpine 3.9 (with Chrome 72). Could you please give it a try ?

```console
$ docker yuzutech/kroki-mermaid:0.0.6
```

Hopefully this version of Chrome will be a bit more verbose :wink:

**Comment by groovytron** [comment] 2019-04-25 09:05
Looks like it's working on my machine now with `yuzutech/kroki-mermaid:0.0.6`. Thanks a lot for your help! :+1: 

Here is the result of this new image.

```log
$ docker run yuzutech/kroki-mermaid:0.0.6
Unable to find image 'yuzutech/kroki-mermaid:0.0.6' locally
0.0.6: Pulling from yuzutech/kroki-mermaid
bdf0201b3a05: Pull complete 
5bceab48fbfa: Pull complete 
7fe54ae0fa03: Pull complete 
41071f686b76: Pull complete 
Digest: sha256:6af748c787c780365c5bbb738d5d8e7565f15d3abbf33606d1c9670286bbdd4b
Status: Downloaded newer image for yuzutech/kroki-mermaid:0.0.6
Chrome accepting connections on endpoint ws://127.0.0.1:43409/devtools/browser/37ed064b-cad9-4077-bb58-70726af29595
```

**Comment by Mogztter** [comment] 2019-04-25 09:32
Awesome news 🎉 
I'll update the documentation accordingly, thanks for your valuable help and your prompt replies 😁

**Comment by Mogztter** [comment] 2019-04-28 08:57
Fixed in https://github.com/yuzutech/kroki/releases/tag/v0.0.6
Thanks again @groovytron for your help :+1:

**Closed by Mogztter** 2019-04-28 08:57 UTC
Labels: bug
